services:
  - type: web
    name: chat-server
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app
    envVars:
      - key: SECRET_KEY
        scope: shared
        value: your-secret-key-render
      - key: PYTHON_VERSION
        value: 3.11.7
